name: Build

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm ci
    - run: npm audit
    - run: npm test
      env:
        CI: true
        working-directory: app

  build:
   needs: test
   runs-on: [ubuntu-latest]
    
   steps:
       - uses: actions/checkout@v2
       - name: Bulid docker image
         env:
           IMAGE_TAG: ${{ github.sha }}
         
         run: |
           docker build -t "$GITHUB_REPOSITORY:$IMAGE_TAG" .
     
 
 
    
